version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: sellr_meilisearch
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      # IMPORTANT: Change this master key in production!
      # Generate a secure key: openssl rand -base64 32
      MEILI_MASTER_KEY: "${MEILI_MASTER_KEY:-ChangeThisToAStrongSecretKeyInProduction123456}"
      MEILI_HTTP_ADDR: "0.0.0.0:7700"
      MEILI_NO_ANALYTICS: "true"
      MEILI_ENV: "${MEILI_ENV:-development}"
      # Optional: Enable CORS for development (disable in production)
      # MEILI_HTTP_PAYLOAD_SIZE_LIMIT: "100 MB"
    volumes:
      - ./data:/meili_data
    networks:
      - sellr_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  sellr_network:
    driver: bridge

volumes:
  meili_data:
    driver: local
